# Generated by Django 4.2.1 on 2024-03-16 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('sku', models.CharField(max_length=10, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('tags', models.CharField(max_length=255, null=True)),
                ('info', models.TextField(null=True)),
                ('price', models.CharField(max_length=30, null=True)),
                ('high_price', models.CharField(max_length=30, null=True)),
                ('discounted_price', models.CharField(max_length=30, null=True)),
                ('discount_rate', models.CharField(max_length=3, null=True)),
                ('image_1', models.ImageField(null=True, upload_to='Product_Img')),
                ('image_2', models.ImageField(null=True, upload_to='Product_Img')),
                ('image_3', models.ImageField(null=True, upload_to='Product_Img')),
                ('image_4', models.ImageField(null=True, upload_to='Product_Img')),
                ('image_5', models.ImageField(null=True, upload_to='Product_Img')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
