# Generated by Django 5.0 on 2024-04-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart_image',
            field=models.ImageField(null=True, upload_to='Product_Img'),
        ),
    ]
