# Generated by Django 5.0.4 on 2024-05-13 17:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0004_product_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cost_price",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="no_of_item",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="per_item_weight",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="total_weight",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="add_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="product",
            name="cart_image",
            field=models.ImageField(upload_to="Product_Img"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount_rate",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="discounted_price",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="high_price",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_1",
            field=models.ImageField(upload_to="Product_Img"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_2",
            field=models.ImageField(upload_to="Product_Img"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_3",
            field=models.ImageField(upload_to="Product_Img"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_4",
            field=models.ImageField(upload_to="Product_Img"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_5",
            field=models.ImageField(upload_to="Product_Img"),
        ),
        migrations.AlterField(
            model_name="product",
            name="info",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
