# Generated by Django 4.2.1 on 2024-03-16 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10, null=True)),
                ('session_id', models.CharField(max_length=255, null=True)),
                ('otp', models.CharField(max_length=6)),
                ('number', models.CharField(max_length=15)),
                ('attempts', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('active', models.BooleanField(default=True)),
                ('token', models.CharField(default='Null', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(default='NULL', max_length=255, null=True)),
                ('number', models.CharField(max_length=15, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('primary_address', models.TextField(null=True)),
                ('secondary_address', models.TextField(null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('pincode', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
