# Generated by Django 4.2.1 on 2024-03-16 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10, null=True)),
                ('session_id', models.CharField(max_length=255, null=True)),
                ('product_id', models.CharField(max_length=10, null=True)),
                ('qty', models.CharField(max_length=10, null=True)),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('order_id', models.CharField(max_length=10)),
                ('shipment', models.BooleanField(default=False)),
                ('payment_id', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=10)),
                ('product_id', models.CharField(max_length=10)),
                ('qty', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=30)),
            ],
        ),
    ]
