# Generated by Django 4.2.1 on 2024-04-08 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
