# Generated by Django 5.0 on 2024-04-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_order_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pg_payment_group',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='pg_payment_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
