# Generated by Django 5.0 on 2024-04-27 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_order_pg_payment_group_order_pg_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payed',
            new_name='paid',
        ),
    ]
