# Generated by Django 5.0 on 2024-05-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0008_order_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PL', 'Order Placed'), ('IT', 'In Transit'), ('DV', 'Delivered')], default='PL', max_length=2),
        ),
    ]
