# Generated by Django 5.0 on 2024-05-05 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0009_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
    ]
