# Generated by Django 5.0 on 2024-05-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0010_remove_order_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pg_payment_group',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
