# Generated by Django 5.0 on 2024-05-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0011_alter_order_pg_payment_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UP', 'Unpaid'), ('PL', 'Order Placed'), ('IT', 'In Transit'), ('DV', 'Delivered')], default='UP', max_length=2),
        ),
    ]
