# Generated by Django 5.0 on 2024-05-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='in_transit_date',
            field=models.DateTimeField(null=True),
        ),
    ]
