# Generated by Django 5.0.4 on 2024-05-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0015_alter_cart_add_date_alter_cart_product_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="made",
            field=models.BooleanField(default=False),
        ),
    ]
